### ISSUE TITLE
error: dialect 'arith' provides no attribute parsing hook

### ISSUE THREAD

**Issue by dellis23** [iree-org/iree-torch#58]
When trying to run [this](https://github.com/iree-org/iree-torch/blob/main/examples/bert.ipynb) notebook:

```python
---------------------------------------------------------------------------
CompilerToolError                         Traceback (most recent call last)
[<ipython-input-3-2bf71e5586d0>](https://localhost:8080/#) in <module>
     26 # cuda - GPU for NVIDIA devices
     27 iree_backend = "llvm-cpu"
---> 28 iree_vmfb = iree_torch.compile_to_vmfb(linalg_on_tensors_mlir, iree_backend)
     29 
     30 print("Loading in IREE")

2 frames
[/usr/local/lib/python3.7/dist-packages/iree/compiler/tools/binaries.py](https://localhost:8080/#) in invoke_immediate(command_line, input_file, immediate_input)
    194     process = subprocess.run(command_line, capture_output=True, **run_args)
    195     if process.returncode != 0:
--> 196       raise CompilerToolError(process)
    197     # Emit stderr contents.
    198     _write_binary_stderr(stderr_handle, process.stderr)

CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
<mlir_parser_buffer>:1:8: error: dialect 'arith' provides no attribute parsing hook
#arith.fastmath<none>
       ^


Invoked with:
 iree-compile /usr/local/lib/python3.7/dist-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvm-embedded-linker-path=/usr/local/lib/python3.7/dist-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.
```

This also happens on a clean install in [this](https://github.com/iree-org/iree-torch/blob/main/examples/regression.py) script.

**Comment by dellis23** [comment]
@silvasean have you seen this issue before?  Not sure if it's a version pinning issue or what.

**Comment by silvasean** [comment]
This is likely due to a mismatch in LLVM version between Torch-MLIR and IREE. I suspect that once IREE rolls forward to the new MLIR version it will go away.

**Comment by dellis23** [comment]
Looks like it's been broken for 17 days: https://github.com/iree-org/iree-torch/actions

Is there nothing in the torch-mlir repo that would catch this being a problem?  That seems like a long time for things to be broken.

**Comment by ramiro050** [comment]
> Looks like it's been broken for 17 days: https://github.com/iree-org/iree-torch/actions

Ah, so it was this change then: https://reviews.llvm.org/D135289

> Is there nothing in the torch-mlir repo that would catch this being a problem? That seems like a long time for things to be broken.

This doesn't seem to be a problem with torch-mlir. The issue is that because IREE is behind on their LLVM version, when importing the MLIR into IREE there is no code to handle the attribute `none` of `arith.fastmath`, which was added 18 days ago.

**Comment by silvasean** [comment]
@ScottTodd -- what is IREE's approximate cadence here for LLVM updates? 18 days out of date feels long.

It looks like an update was added business-day-"yesterday" so let's see if it works now: https://github.com/iree-org/iree/commits/main/third_party

**Comment by ScottTodd** [comment]
> @ScottTodd -- what is IREE's approximate cadence here for LLVM updates? 18 days out of date feels long.

At least weekly, sometimes daily. There can be delays for various reasons. I'd check with @MaheshRavishankar or someone else from the commit history to https://github.com/iree-org/iree/commits/main/third_party.

**Comment by stellaraccident** [comment]
Sounds like you might be pulling the official release from pypi vs the nightly from github.

**Comment by ScottTodd** [comment]
Oh, good point.

https://github.com/iree-org/iree-torch/blob/27f7a4f2c87678e6f526f91ed3d5369585d3f2c1/requirements.txt#L1-L4

this should be using https://iree-org.github.io/iree/pip-release-links.html

**Comment by dellis23** [comment]
Thanks for the catch.  Updated in https://github.com/iree-org/iree-torch/pull/59

**Comment by dellis23** [comment]
This is happening again: https://discord.com/channels/689900678990135345/689900680009482386/1040309303069900880
