### ISSUE TITLE
AttributeError: module 'torch_mlir' has no attribute 'compile'

### ISSUE THREAD

**Issue by zhping5678** [iree-org/iree-torch#65]
When I tried to run the demo 'examples/bert.py', it reported 'AttributeError: module 'torch_mlir' has no attribute 'compile'. I have installed required packages.

**Comment by dellis23** [comment]
Did you install torch-mlir via pypi instead of from https://llvm.github.io/torch-mlir/package-index/ by chance?  The version on PyPI is just a dummy release right now until we get PyPI publishing working correctly (unfortunately I had to create a dummy release in order to request PyPI to up our per-release file limit; I had a feeling that might be confusing).

**Comment by bsergean** [comment]
There is a colab notebook I tried to run, which is linked in the iree documentation (the pytorch part), and it display that same error as well.

-> https://colab.research.google.com/github/iree-org/iree-torch/blob/main/examples/bert.ipynb

Not sure who owns it and how to fix it.

The install steps use the llvm/torch-mlir way of installing things btw.
```
pip install -f https://llvm.github.io/torch-mlir/package-index/ torch-mlir
```

**Comment by bsergean** [comment]
ps: that second line looks really strange to me, the index having an html part. (pip-release-links.html)

```
!pip install -f https://iree-org.github.io/iree/pip-release-links.html iree-compiler iree-runtime
```

**Comment by bsergean** [comment]
I also tried to use the daily torch_mlir listed here -> https://github.com/llvm/torch-mlir/releases

After a pip install using this, I can see 'files', but still no torch_mlir.

```
(venv) ~$ find venv | grep mlir
venv/lib/python3.9/site-packages/torch_mlir-0.0.0.dist-info
venv/lib/python3.9/site-packages/torch_mlir-0.0.0.dist-info/RECORD
venv/lib/python3.9/site-packages/torch_mlir-0.0.0.dist-info/LICENSE
venv/lib/python3.9/site-packages/torch_mlir-0.0.0.dist-info/WHEEL
venv/lib/python3.9/site-packages/torch_mlir-0.0.0.dist-info/top_level.txt
venv/lib/python3.9/site-packages/torch_mlir-0.0.0.dist-info/REQUESTED
venv/lib/python3.9/site-packages/torch_mlir-0.0.0.dist-info/INSTALLER
venv/lib/python3.9/site-packages/torch_mlir-0.0.0.dist-info/METADATA
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/_mlirHlo.cpython-39-darwin.so
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/_mlirLinalgPasses.cpython-39-darwin.so
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/__init__.py
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/__pycache__
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/__pycache__/__init__.cpython-39.pyc
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/_ireeDialects.cpython-39-darwin.so
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/_ireecTransforms.cpython-39-darwin.so
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/_mlir
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/_mlir/ir.pyi
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/_mlir/__init__.pyi
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/_mlir/passmanager.pyi
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/_mlir/dialects
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/_mlir/dialects/pdl.pyi
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/_mlirDialectsLinalg.cpython-39-darwin.so
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/libIREECompilerAggregateCAPI.dylib
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/_mlir.cpython-39-darwin.so
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/iree-lld
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/iree-compile
venv/lib/python3.9/site-packages/iree/compiler/_mlir_libs/_mlirDialectsPDL.cpython-39-darwin.so
venv/lib/python3.9/site-packages/torch_mlir
venv/lib/python3.9/site-packages/torch_mlir/__init__.py
venv/lib/python3.9/site-packages/torch_mlir/__pycache__
venv/lib/python3.9/site-packages/torch_mlir/__pycache__/__init__.cpython-39.pyc
```

**Comment by bsergean** [comment]
Thanks. I have actually cloned this repo (iree-torch) and I am installing the deps directly by reading the requirement file, that works better but now I'm getting an error installing pillow ... I'm using the macbrew python (3.9), in recent version of osx I think there's a bundled 3.8 python, will try that one ...

**Comment by dellis23** [comment]
Thanks @bsergean, I'm getting the same error when I try running the notebook too.  Will look into it.

**Comment by dellis23** [comment]
I think this might be because colab rolled the default python version to 3.8.

**Comment by dellis23** [comment]
I've deleted the dummy 0.0.0 install from pypi, so at the very least that confusion should be gone.  I still see it when I'm trying to install, so it might take some time for caches to appear.  @powderluv is going to build new packages for the new Python versions, which should fix this problem.

**Comment by dellis23** [comment]
Thanks for the heads up. That actually won't fix it for you then. I think we need to consider building a generic torch-mlir Python package either in addition to or instead of trying to build for a handful of specific Python versions.  /cc @powderluv

**Comment by bsergean** [comment]
I can install python 3.10 and try with this version. There’s something called py-env which makes switching python version easier those days, but I haven’t tried it on macOS yet.

**Comment by GMNGeoffrey** [comment]
I'm currently seeing a similar error in IREE's samples build:

```
/usr/bin/clang++-9 main.c -flto -O2 -I../../runtime/src/ -L/tmp/iree-build-runtime//build_tools/third_party/flatcc/ -L/tmp/iree-build-runtime//runtime/src/iree/runtime/ -L/tmp/iree-build-runtime//third_party/cpuinfo/ -L/tmp/iree-build-runtime//third_party/cpuinfo/deps/clog -liree_runtime_unified -lflatcc_parsing -lcpuinfo -lclog -ldl -lpthread -o native-training
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
+ python native_training.py /tmp/native_training.vmfb
Traceback (most recent call last):
  File "native_training.py", line 11, in <module>
    from functorch._src.compile_utils import strip_overloads
ModuleNotFoundError: No module named 'functorch._src.compile_utils'
```

https://github.com/iree-org/iree/actions/runs/3643985501/jobs/6152755452 and https://buildkite.com/iree/iree-samples/builds/563#0184e9f1-f3e6-415f-81d7-d9b8d088cb25/41-5629

@dellis23 are you investigating this?

**Comment by powderluv** [comment]
the function signature has changed in the latest nightly for functorch. A similar fix landed in torch-mlir

**Comment by dellis23** [comment]
> I'm currently seeing a similar error in IREE's samples build:
> 
> ```
> /usr/bin/clang++-9 main.c -flto -O2 -I../../runtime/src/ -L/tmp/iree-build-runtime//build_tools/third_party/flatcc/ -L/tmp/iree-build-runtime//runtime/src/iree/runtime/ -L/tmp/iree-build-runtime//third_party/cpuinfo/ -L/tmp/iree-build-runtime//third_party/cpuinfo/deps/clog -liree_runtime_unified -lflatcc_parsing -lcpuinfo -lclog -ldl -lpthread -o native-training
> clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
> + python native_training.py /tmp/native_training.vmfb
> Traceback (most recent call last):
>   File "native_training.py", line 11, in <module>
>     from functorch._src.compile_utils import strip_overloads
> ModuleNotFoundError: No module named 'functorch._src.compile_utils'
> ```
> 
> https://github.com/iree-org/iree/actions/runs/3643985501/jobs/6152755452 and https://buildkite.com/iree/iree-samples/builds/563#0184e9f1-f3e6-415f-81d7-d9b8d088cb25/41-5629
> 
> @dellis23 are you investigating this?

Yeah, the fix was merged here: https://github.com/iree-org/iree/commit/fcae6d71895c7d13cef0637657219c9ebf931249

**Comment by zhping5678** [comment]
I installed torch_mlir by compiling source code and setting environment path, as development.md says.
